#!/bin/sh
set -e
# Automatically added by dh_installudev
if [ "$1" = configure ]; then
	if [ -e "/etc/udev/rules.d/92_libccid.rules" ]; then
		echo "Preserving user changes to /etc/udev/rules.d/92-libccid.rules ..."
		if [ -e "/etc/udev/rules.d/92-libccid.rules" ]; then
			mv -f "/etc/udev/rules.d/92-libccid.rules" "/etc/udev/rules.d/92-libccid.rules.dpkg-new"
		fi
		mv -f "/etc/udev/rules.d/92_libccid.rules" "/etc/udev/rules.d/92-libccid.rules"
	fi
fi
# End automatically added section
